linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gosec

run:
  modules-download-mode: vendor
