{
 "title": "Finality Prysm",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Head Slot (beacon)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "beacon_head_slot{service=~\"beacon-follower-prysm|beacon-follower1-prysm|beacon-follower2-prysm|beacon-follower3-prysm|beacon-follower4-prysm|beacon-follower5-prysm|beacon-follower6-prysm|beacon-prysm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized Epoch (beacon)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{service=~\"beacon-follower-prysm|beacon-follower1-prysm|beacon-follower2-prysm|beacon-follower3-prysm|beacon-follower4-prysm|beacon-follower5-prysm|beacon-follower6-prysm|beacon-prysm\"}  != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "beacon_finalized_epoch{service=~\"beacon-follower-prysm|beacon-follower1-prysm|beacon-follower2-prysm|beacon-follower3-prysm|beacon-follower4-prysm|beacon-follower5-prysm|beacon-follower6-prysm|beacon-prysm\"}  != 0",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 9 },
   "targets": [
    { "expr": "beacondb_all_deposits", "legendFormat": "__auto" },
    {
     "expr": "powchain_valid_deposits_received",
     "legendFormat": "__auto"
    },
    {
     "expr": "current_eth1_data_deposit_count",
     "legendFormat": "__auto"
    },
    { "expr": "beacondb_pending_deposits", "legendFormat": "__auto" },
    {
     "expr": "beacon_processed_deposits_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalization Lag (epochs)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(beacon_current_justified_epoch)-max(beacon_previous_justified_epoch)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregate Attestation Verification Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(gossip_aggregate_attestation_verification_milliseconds_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestation Processing ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "rate(process_attestations_milliseconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replay Blocks Sum",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 14 },
   "targets": [
    { "expr": "replay_blocks_count_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Late Attestation Past 5m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "rate(attestation_too_late_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache Misses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Checkpoint State Cache Miss %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(check_point_state_cache_miss[5m])/(rate(check_point_state_cache_miss[5m])+rate(check_point_state_cache_hit[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync State Cache Miss %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "rate(sync_head_state_miss[5m])/(rate(sync_head_state_miss[5m])+rate(sync_head_state_hit[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Committee Index Miss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "rate(sync_committee_index_cache_miss_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestation Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "rate(attestation_cache_miss[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Committee Miss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 25 },
   "targets": [
    { "expr": "rate(committee_cache_miss[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hot State Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 25 },
   "targets": [
    { "expr": "rate(hot_state_cache_miss[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Next slot cache miss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "targets": [
    { "expr": "rate(next_slot_cache_miss[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Attestations (past 5m)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(validator_failed_attestations[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}