# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

# -- Number of replicas
replicas: 1

image:
  # -- Lighthouse container image repository
  repository: sigp/lighthouse
  # -- Lighthouse container image tag
  tag: v4.1.0
  # -- Lighthouse container pull policy
  pullPolicy: IfNotPresent

# -- Mode can be 'beacon','validator' or 'bootnode'
mode: "beacon"

# -- Extra args for the lighthouse container
extraArgs:
  - --boot-nodes enr:-MK4QM67BhLd6GJRyS0eN5meaNNenQoQB3NYlIjweYdDmnPCDcbdX8BtG1_hqfA5PnLoXDECIdFtwJkAVzx8UAWYic6GAYm8rOLYh2F0dG5ldHOI__________-EZXRoMpA919pyIAAAkv__________gmlkgnY0gmlwhAr1ABSJc2VjcDI1NmsxoQJWH5D7S4145jEEMuBvUzQFic2PXHF0xax2t-XUoTkD6IhzeW5jbmV0cw-DdGNwgjLIg3VkcIIyyA,/ip4/10.244.1.66/tcp/13000/p2p/16Uiu2HAm1DrxbnunPrB6r5x8egB1X3ETMgzC8cSganDcbuLEoHfm,/ip4/10.245.0.20/tcp/13000/p2p/16Uiu2HAm1DrxbnunPrB6r5x8egB1X3ETMgzC8cSganDcbuLEoHfm,/ip4/10.245.0.20/tcp/13000/p2p/16Uiu2HAm1DrxbnunPrB6r5x8egB1X3ETMgzC8cSganDcbuLEoHfm
  - --execution-endpoint http://geth-follower.default:8551
  - --suggested-fee-recipient 0x123463a4b065722e99115d6c222f267d9cabb524
  - --network-dir=/data
  - --testnet-dir=/data
  - --enable-private-discovery
  # - --libp2p-addresses /ip4/10.244.0.189/tcp/13000/p2p/16Uiu2HAkvufmPRJg9D7MmimY369BFm2KFGW9ChCb9WMQnJVkj34H,/ip4/10.244.0.90/tcp/13000/p2p/16Uiu2HAmGxwYc81C6um7HJg1YPmU9XovGVAjWzK5TGAoWxYoS5jL,/ip4/10.244.1.103/tcp/13000/p2p/16Uiu2HAmH4jrvYE5tA3rGH3Q3TRrLikjsGZVEb4joUVVftkdo1Ms,/ip4/10.244.0.171/tcp/13000/p2p/16Uiu2HAm9JaUAtQLchcRwkoT6j9eg1PAG54fiipSSWKCBHWNkeLV,/ip4/10.244.0.3/tcp/13000/p2p/16Uiu2HAmMCnYVUwno99dJ5YwaB48eVAhkHv4TTjBJ8gvbPNwzgAh,/ip4/10.244.1.78/tcp/13000/p2p/16Uiu2HAkuXDznQ82AQuEVGwV9ZFgaqUpc2bfznD3JfLR5gFCDrdC
  - --trusted-peers 16Uiu2HAm1DrxbnunPrB6r5x8egB1X3ETMgzC8cSganDcbuLEoHfm
  - --disable-peer-scoring
  - --target-peers 1
  ## Example for beacon mode
  #- --network=goerli
  #- --execution.urls=http://your-eth1-node:8551
  #- --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io
  ##
  ## Example for validator mode
  #- --network=goerli
  #- --enable-doppelganger-protection
  #- --beacon-nodes=http://lighthouse-beacon:5052

# -- Additional init containers
initContainers:
  - name: copy-genesis-ssz
    image: busybox:latest
    command: ["wget", "http://geth.default:10000/genesis.ssz", "--directory-prefix", "/data"]
    volumeMounts:
    - name: storage
      mountPath: "/data"
  - name: copy-genesis-config
    image: busybox:latest
    command: ["wget", "http://geth.default:10000/config-lighthouse.yml", "--directory-prefix", "/data"]
    volumeMounts:
    - name: storage
      mountPath: "/data"
  - name: rename-config
    image: busybox:latest
    command: ["mv", "/data/config-lighthouse.yml", "/data/config.yaml"]
    volumeMounts:
    - name: storage
      mountPath: "/data"
  - name: create-deploy-block
    image: busybox:latest
    command: ["sh", "-c", "echo \"0\" > /data/deploy_block.txt"]
    volumeMounts:
    - name: storage
      mountPath: "/data"




# -- JWT secret used by client as a secret. Change this value.
jwt: ecb22bc24e7d4061f7ed690ccd5846d7d73f5d2b9733267e12f56790398d908a

# -- Checkpoint Sync
checkpointSync:
  enabled: false
  url: ""

# -- Template used for the default beacon command
# @default -- See `values.yaml`
#     --disable-enr-auto-update
defaultBeaconCommandTemplate: |
  - sh
  - -ac
  - >
  {{- if .Values.p2pNodePort.enabled }}
    . /env/init-nodeport;
  {{- end }}
    exec lighthouse
    beacon_node
    --datadir=/data
    --disable-upnp
  {{- if .Values.p2pNodePort.enabled }}
    {{- if not (contains "--enr-address=" (.Values.extraArgs | join ",")) }}
    --enr-address=$EXTERNAL_IP
    {{- end }}
    {{- if not (contains "--enr-tcp-port=" (.Values.extraArgs | join ",")) }}
    --enr-tcp-port=$EXTERNAL_PORT
    {{- end }}
    {{- if not (contains "--enr-udp-port=" (.Values.extraArgs | join ",")) }}
    --enr-udp-port=$EXTERNAL_PORT
    {{- end }}
  {{- else }}
    {{- if not (contains "--enr-address=" (.Values.extraArgs | join ",")) }}
    --enr-address=$(POD_IP)
    {{- end }}
    {{- if not (contains "--enr-tcp-port=" (.Values.extraArgs | join ",")) }}
    --enr-tcp-port={{ include "lighthouse.p2pPort" . }}
    {{- end }}
    {{- if not (contains "--enr-udp-port=" (.Values.extraArgs | join ",")) }}
    --enr-udp-port={{ include "lighthouse.p2pPort" . }}
    {{- end }}
  {{- end }}
    --listen-address=0.0.0.0
    --port={{ include "lighthouse.p2pPort" . }}
    --discovery-port={{ include "lighthouse.p2pPort" . }}
    --http
    --http-address=0.0.0.0
    --http-port={{ .Values.httpPort }}
    --execution-jwt=/data/jwt.hex
    --metrics
    --metrics-address=0.0.0.0
    --metrics-port={{ .Values.metricsPort }}
  {{- if .Values.checkpointSync.enabled }}
    --checkpoint-sync-url={{ tpl .Values.checkpointSync.url $ }}
  {{- end }}
  {{- range .Values.extraArgs }}
    {{ tpl . $ }}
  {{- end }}

# -- Template used for the default validator command
# @default -- See `values.yaml`
defaultValidatorCommandTemplate: |
  - sh
  - -ac
  - >
    exec lighthouse
    validator
    --metrics
    --metrics-address=0.0.0.0
    --metrics-port={{ .Values.metricsPort }}
  {{- range .Values.extraArgs }}
    {{ tpl . $ }}
  {{- end }}

# -- Template used for the default validator command
# @default -- See `values.yaml`
defaultBootnodeCommandTemplate: |
  - sh
  - -ac
  - >
  {{- if .Values.p2pNodePort.enabled }}
    . /env/init-nodeport;
  {{- end }}
    exec lighthouse
    boot_node
    --datadir=/data
    --listen-address=0.0.0.0
    --port={{ include "lighthouse.p2pPort" . }}
  {{- range .Values.extraArgs }}
    {{ . }}
  {{- end }}
  {{- if .Values.p2pNodePort.enabled }}
    --enr-port=$EXTERNAL_PORT
    --enr-address=$EXTERNAL_IP
  {{- else }}
    --enr-port={{ include "lighthouse.p2pPort" . }}
    --enr-address=$(POD_IP)
  {{- end }}


# -- Legacy way of overwriting the default command. You may prefer to change defaultCommandTemplates instead.
customCommand: []

# When p2pNodePort is enabled, your P2P port will be exposed via service type NodePort.
# This will generate a service for each replica, with a port binding via NodePort.
# This is useful if you want to expose and announce your node to the Internet.
p2pNodePort:
  # -- Expose P2P port via NodePort
  enabled: false
  # -- NodePort to be used
  port: 31000
  initContainer:
    image:
      # -- Container image to fetch nodeport information
      repository: lachlanevenson/k8s-kubectl
      # -- Container tag
      tag: v1.21.3
      # -- Container pull policy
      pullPolicy: IfNotPresent

ingress:
  # -- Ingress resource for the HTTP API
  enabled: false
  # -- Annotations for Ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host
  hosts:
    - host: chart-example.local
      paths: []
  # -- Ingress TLS
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Affinity configuration for pods
affinity: {}

# -- Image pull secrets for Docker images
imagePullSecrets: []

# -- Annotations for the StatefulSet
annotations: {}

# -- Liveness probe
# @default -- See `values.yaml`
livenessProbe:
  tcpSocket:
    port: http-api
  initialDelaySeconds: 60
  periodSeconds: 120

# -- Readiness probe
# @default -- See `values.yaml`
readinessProbe:
  tcpSocket:
    port: http-api
  initialDelaySeconds: 10
  periodSeconds: 10

# -- P2P Port
p2pPort: 9000

# -- HTTP Port
httpPort: 5052

# -- Metrics Port
metricsPort: 5054

# -- Node selector for pods
nodeSelector: {}

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: false
  # -- Use an existing PVC when persistence.enabled
  existingClaim: null
  # -- Access mode for the volume claim template
  accessModes:
  - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 20Gi
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: null
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something

# -- Pod labels
podLabels: {}

# -- Pod annotations
podAnnotations: {}

# -- Pod management policy
podManagementPolicy: OrderedReady

# -- Pod priority class
priorityClassName: null

rbac:
  # -- Specifies whether RBAC resources are to be created
  create: true
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  clusterRules:
     # Required to obtain the nodes external IP
    - apiGroups: [""]
      resources:
      - "nodes"
      verbs:
      - "get"
      - "list"
      - "watch"
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  rules:
    # Required to get information about the serices nodePort.
    - apiGroups: [""]
      resources:
      - "services"
      verbs:
      - "get"
      - "list"
      - "watch"

# -- Resource requests and limits
resources: {}
# limits:
#   cpu: 500m
#   memory: 2Gi
# requests:
#   cpu: 300m
#   memory: 1Gi

# -- The security context for pods
# @default -- See `values.yaml`
securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

# -- The security context for containers
# @default -- See `values.yaml`
containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- How long to wait until the pod is forcefully terminated
terminationGracePeriodSeconds: 300

# -- Tolerations for pods
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Topology Spread Constraints for pods
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
topologySpreadConstraints: []

# -- Define the PodDisruptionBudget spec
# If not set then a PodDisruptionBudget will not be created
podDisruptionBudget: {}
# minAvailable: 1
# maxUnavailable: 1

# -- Update stategy for the Statefulset
updateStrategy:
  # -- Update stategy type
  type: RollingUpdate


# -- Additional containers
extraContainers: []

# -- Additional volumes
extraVolumes: []

# -- Additional volume mounts
extraVolumeMounts: []

# -- Additional ports. Useful when using extraContainers
extraPorts: []

# -- Additional env variables
extraEnv: []

# -- Additional env variables injected via a created secret
secretEnv: {}
# MY_PASSWORD: supersecret

initChownData:
  # -- Init container to set the correct permissions to access data directories
  enabled: true
  image:
    # -- Container repository
    repository: busybox
    # -- Container tag
    tag: "1.34.0"
    # -- Container pull policy
    pullPolicy: IfNotPresent
  # -- Resource requests and limits
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: true
  # -- Path to scrape
  path: /metrics
  # -- Alternative namespace for ServiceMonitor
  namespace: null
  # -- Additional ServiceMonitor labels
  labels: {}
  # -- Additional ServiceMonitor annotations
  annotations: {}
  # -- ServiceMonitor scrape interval
  interval: 1m
  # -- ServiceMonitor scheme
  scheme: http
  # -- ServiceMonitor TLS configuration
  tlsConfig: {}
  # -- ServiceMonitor scrape timeout
  scrapeTimeout: 30s
  # -- ServiceMonitor relabelings
  relabelings: []

resources:
  requests:
    memory: "2Gi"
  limits:
    memory: "2Gi"