# -- Mode can be 'beacon' or 'validator'
mode: "validator"

# -- Extra args for the prysm container
extraArgs:
  - --beacon-rpc-provider=beacon-prysm.default:4000
  - --chain-config-file=/data/config.yaml
  - --interop-num-validators=2048
  - --interop-start-index=0
  - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524

# -- JWT secret used by client as a secret. Change this value.
jwt: ecb22bc24e7d4061f7ed690ccd5846d7d73f5d2b9733267e12f56790398d908a


# -- Additional init containers
initContainers:
  - name: copy-genesis-ssz
    image: busybox:latest
    command: ["wget", "http://genesis-generator.default:8000/custom_config_data/genesis.ssz", "--directory-prefix", "/data"]
    volumeMounts:
    - name: storage
      mountPath: "/data"
  - name: copy-genesis-config
    image: busybox:latest
    command: ["wget", "http://genesis-generator.default:8000/custom_config_data/config.yaml", "--directory-prefix", "/data"]
    volumeMounts:
    - name: storage
      mountPath: "/data"
  - name: copy-network-key
    image: busybox:latest
    command: ["wget", "http://geth.default:10000/network-keys", "--directory-prefix", "/data"]
    volumeMounts:
    - name: storage
      mountPath: "/data"
  - name: generate-validators
    image: bensamstob/ethereum-genesis-generator:latest
    command: ["/usr/bin/sh","-c", "/usr/local/bin/eth2-val-tools deposit-data --as-json-list --fork-version 0x20000089 --source-max 2048 --source-min 0 --validators-mnemonic 'giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete' --withdrawals-mnemonic 'giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete' > /data/keys.json"]
    #command: ["/usr/bin/sh","-c", "/usr/local/bin/eth2-val-tools", "deposit-data", "--fork-version", "0x20000089", "--source-max", "2048", "--source-min", "0", "--validators-mnemonic", "'giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete'", "--withdrawals-mnemonic", "'giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete'", ">", "/data/keys.json"]
    volumeMounts:
    - name: storage
      mountPath: "/data"


# -- Liveness probe
# @default -- See `values.yaml`
livenessProbe:
  tcpSocket:
    port: metrics
  initialDelaySeconds: 60
  periodSeconds: 120

# -- Readiness probe
# @default -- See `values.yaml`
readinessProbe:
  tcpSocket:
    port: metrics
  initialDelaySeconds: 10
  periodSeconds: 10


serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: true

resources:
  requests:
    memory: "300Mi"
  limits:
    memory: "300Mi"


nodeType: validator